[package]
name = "realms"
version = "0.2.0"
edition = "2021"
authors = ["Dylan Rogers <opendylan@proton.me>"]
description = "A powerful and lightweight graphics library for making Rust games"
documentation = "https://docs.rs/realms"
homepage = "https://github.com/dylanopen/realms"
repository = "https://github.com/dylanopen/realms"
license = "GPL-3.0-or-later"
keywords = ["game", "graphics", "pixel", "window", "gamedev"]
categories = ["graphics", "games", "rendering", "game-engines", "gui"]

[dependencies]
minifb = "0.27.0"
ril = { version = "0.10.3", features = ["png"] }

