[package]
name = "realms"
version = "1.0.0"
edition = "2024"
license = "MIT"
keywords = ["gamedev", "graphics", "game", "engine", "opengl"]
categories = ["game-development", "game-engines", "graphics", "rendering", "rendering::engine"]

[lib]
doctest = false

[dependencies]
gl = "0.14.0"
glfw = "0.59.0"
image = "0.19.0"
